### ISSUE TITLE
Functionality doesn't match CyrptoJS, no documented alternative

### ISSUE THREAD

**Issue by kyeotic** [gwjjeff/cryptojs#2]
The CryptoJS documentation offers this single example of using PBKDF2:

```
var salt = CryptoJS.lib.WordArray.random(128/8);

var key128Bits = CryptoJS.PBKDF2("Secret Passphrase", salt, { keySize: 128/32 });
var key256Bits = CryptoJS.PBKDF2("Secret Passphrase", salt, { keySize: 256/32 });
var key512Bits = CryptoJS.PBKDF2("Secret Passphrase", salt, { keySize: 512/32 });

var key512Bits1000Iterations = CryptoJS.PBKDF2("Secret Passphrase", salt, { keySize: 512/32, iterations: 1000 });
```

The first line will not work with this, indicating WordArray is not a method. Is there an alterante method in the module for generating a salt?

Also, when calling the second line with a salt generated manually, I get an invalid array length error.

How can this module be used to generate a hash? You have no examples.

**Comment by Chandrakala14** [comment]
Hi tyrsius,
I am also facing same issue, Did you find solution ?

**Comment by kyeotic** [comment]
@Chandrakala14 No I didn't.

**Comment by crcer** [comment]
Is there any solution now?
I am also facing this issue....

**Comment by garrows** [comment]
I think your problem is `salt` is not a string.

**Comment by kyeotic** [comment]
@garrows You think the reason that the first line throws an error is that the variable `salt` is not a string? I don't see how that could be possible. The value of `salt` is not accessed in the first line. The variable is declared and assigned on that line, it doesn't even get a value because the assignment throws an error.
